// src/pages/index.tsx

import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useGlobalState } from '../context/GlobalState';
import Sidebar from '../components/Sidebar/Sidebar';
import Navbar from '../components/Navbar/Navbar';
import EventForm from '../components/eventform';
import { Box } from '@radix-ui/themes';

const Home: NextPage = () => {
  const [state, dispatch] = useGlobalState();

  return (
    <Box className={styles.container}>
      <Box className="main-wrapper">
        <Sidebar />
        <Box className="content">
          <Navbar />
          <EventForm />
        </Box>
      </Box>

      <Head>
        <title>Next.js Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={() => dispatch({ type: 'SET_USER', payload: 'John Doe' })}>
          Set User
        </button>

        <p>{state.user ? `User: ${state.user}` : 'No user set'}</p>
      </main> */}
    </Box>
  );
};

export default Home;
